In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

In [2]:
from pathlib import Path
import pandas as pd

BASE_DIR = Path(r"E:\Mutual Fund Blue")
DATA_PATH = BASE_DIR / "data" / "processed" / "all_nav_history.csv"

print("Looking for:", DATA_PATH)
print("File exists:", DATA_PATH.exists())

df = pd.read_csv(DATA_PATH)

df["date"] = pd.to_datetime(df["date"])
df["nav"] = pd.to_numeric(df["nav"])

df = df.sort_values(["scheme", "date"])

print("Shape:", df.shape)
print("Schemes:", df["scheme"].unique())

df.head()

Looking for: E:\Mutual Fund Blue\data\processed\all_nav_history.csv
File exists: True
Shape: (20026, 3)
Schemes: <StringArray>
[     'Axis_Bluechip', 'HDFC_Top100_Direct',     'ICICI_Bluechip',
     'Kotak_Bluechip',   'Nippon_Large_Cap',       'SBI_Bluechip']
Length: 6, dtype: str

              scheme       date      nav
13084  Axis_Bluechip 2012-12-31  23.9920
13085  Axis_Bluechip 2013-01-01  23.9979
13086  Axis_Bluechip 2013-01-02  24.0036
13087  Axis_Bluechip 2013-01-03  24.0092
13088  Axis_Bluechip 2013-01-04  24.0147

In [3]:
df["daily_return"] = (
    df.groupby("scheme")["nav"]
      .pct_change()
)

df[["scheme", "date", "nav", "daily_return"]].head(10)

              scheme       date      nav  daily_return
13084  Axis_Bluechip 2012-12-31  23.9920           NaN
13085  Axis_Bluechip 2013-01-01  23.9979      0.000246
13086  Axis_Bluechip 2013-01-02  24.0036      0.000238
13087  Axis_Bluechip 2013-01-03  24.0092      0.000233
13088  Axis_Bluechip 2013-01-04  24.0147      0.000229
13089  Axis_Bluechip 2013-01-06  24.0258      0.000462
13090  Axis_Bluechip 2013-01-07  24.0314      0.000233
13091  Axis_Bluechip 2013-01-08  24.0369      0.000229
13092  Axis_Bluechip 2013-01-09  24.0424      0.000229
13093  Axis_Bluechip 2013-01-10  24.0479      0.000229

In [4]:
df["daily_return"] = (
    df.groupby("scheme")["nav"]
      .pct_change()
)

df[["scheme", "date", "nav", "daily_return"]].head(10)

              scheme       date      nav  daily_return
13084  Axis_Bluechip 2012-12-31  23.9920           NaN
13085  Axis_Bluechip 2013-01-01  23.9979      0.000246
13086  Axis_Bluechip 2013-01-02  24.0036      0.000238
13087  Axis_Bluechip 2013-01-03  24.0092      0.000233
13088  Axis_Bluechip 2013-01-04  24.0147      0.000229
13089  Axis_Bluechip 2013-01-06  24.0258      0.000462
13090  Axis_Bluechip 2013-01-07  24.0314      0.000233
13091  Axis_Bluechip 2013-01-08  24.0369      0.000229
13092  Axis_Bluechip 2013-01-09  24.0424      0.000229
13093  Axis_Bluechip 2013-01-10  24.0479      0.000229

In [5]:
performance = []

for scheme, group in df.groupby("scheme"):

    group = group.sort_values("date").dropna(subset=["daily_return"])

    first_nav = group["nav"].iloc[0]
    last_nav = group["nav"].iloc[-1]
    trading_days = len(group)

    annualized_return = (
        (last_nav / first_nav) ** (252 / trading_days)
    ) - 1

    performance.append({
        "scheme": scheme,
        "first_date": group["date"].iloc[0],
        "last_date": group["date"].iloc[-1],
        "first_nav": first_nav,
        "last_nav": last_nav,
        "trading_days": trading_days,
        "annualized_return": annualized_return
    })

performance_df = pd.DataFrame(performance)

performance_df.round(4)

C:\Users\DELL\AppData\Local\Temp\ipykernel_15440\575316321.py:27: UserWarning: obj.round has no effect with datetime, timedelta, or period dtypes. Use obj.dt.round(...) instead.
  performance_df.round(4)

,scheme,first_date,last_date,first_nav,last_nav,trading_days,annualized_return
0,Axis_Bluechip,2013-01-01,2026-07-24,23.9979,6242.1652,3602,0.4756
1,HDFC_Top100_Direct,2013-11-19,2026-07-24,13.1068,204.8535,3128,0.2479
2,ICICI_Bluechip,2013-01-03,2026-07-24,15.0737,108.0484,3344,0.1600
3,Kotak_Bluechip,2013-01-08,2026-07-24,30.6239,249.2715,3338,0.1715
4,Nippon_Large_Cap,2013-01-03,2026-07-24,14.7305,99.3273,3335,0.1551
5,SBI_Bluechip,2013-01-03,2026-07-24,103.0306,106.5961,3273,0.0026

In [6]:
volatility = (
    df.groupby("scheme")["daily_return"]
      .std()
      .mul(np.sqrt(252))
)

performance_df = performance_df.merge(
    volatility.rename("annualized_volatility"),
    on="scheme"
)

performance_df[
    ["scheme", "annualized_return", "annualized_volatility"]
].round(4)

NameError: name 'np' is not defined

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

In [8]:
volatility = (
    df.groupby("scheme")["daily_return"]
      .std()
      .mul(np.sqrt(252))
)

performance_df = performance_df.merge(
    volatility.rename("annualized_volatility"),
    on="scheme"
)

performance_df[
    ["scheme", "annualized_return", "annualized_volatility"]
].round(4)

               scheme  annualized_return  annualized_volatility
0       Axis_Bluechip             0.4756                26.1968
1  HDFC_Top100_Direct             0.2479                 0.1518
2      ICICI_Bluechip             0.1600                    NaN
3      Kotak_Bluechip             0.1715                 0.1539
4    Nippon_Large_Cap             0.1551                 0.1665
5        SBI_Bluechip             0.0026                 0.0867

In [9]:
max_drawdowns = []

for scheme, group in df.groupby("scheme"):
    group = group.sort_values("date").copy()

    running_max = group["nav"].cummax()
    drawdown = (group["nav"] / running_max) - 1

    max_drawdowns.append({
        "scheme": scheme,
        "max_drawdown": drawdown.min()
    })

drawdown_df = pd.DataFrame(max_drawdowns)

performance_df = performance_df.merge(
    drawdown_df,
    on="scheme"
)

performance_df[
    ["scheme", "max_drawdown"]
].round(4)

               scheme  max_drawdown
0       Axis_Bluechip       -0.0139
1  HDFC_Top100_Direct       -0.4026
2      ICICI_Bluechip       -1.0000
3      Kotak_Bluechip       -0.3343
4    Nippon_Large_Cap       -0.3996
5        SBI_Bluechip       -0.3665

In [10]:
performance_df.round(4)

C:\Users\DELL\AppData\Local\Temp\ipykernel_15440\2127805111.py:1: UserWarning: obj.round has no effect with datetime, timedelta, or period dtypes. Use obj.dt.round(...) instead.
  performance_df.round(4)

,scheme,first_date,last_date,first_nav,last_nav,trading_days,annualized_return,annualized_volatility,max_drawdown
0,Axis_Bluechip,2013-01-01,2026-07-24,23.9979,6242.1652,3602,0.4756,26.1968,-0.0139
1,HDFC_Top100_Direct,2013-11-19,2026-07-24,13.1068,204.8535,3128,0.2479,0.1518,-0.4026
2,ICICI_Bluechip,2013-01-03,2026-07-24,15.0737,108.0484,3344,0.1600,NaN,-1.0000
3,Kotak_Bluechip,2013-01-08,2026-07-24,30.6239,249.2715,3338,0.1715,0.1539,-0.3343
4,Nippon_Large_Cap,2013-01-03,2026-07-24,14.7305,99.3273,3335,0.1551,0.1665,-0.3996
5,SBI_Bluechip,2013-01-03,2026-07-24,103.0306,106.5961,3273,0.0026,0.0867,-0.3665

In [11]:
benchmark = "HDFC_Top100_Direct"

returns = df.pivot(
    index="date",
    columns="scheme",
    values="daily_return"
)

benchmark_returns = returns[benchmark]

betas = {}

for scheme in returns.columns:
    if scheme == benchmark:
        betas[scheme] = 1.0
        continue

    combined = pd.concat(
        [returns[scheme], benchmark_returns],
        axis=1
    ).dropna()

    covariance = combined.iloc[:, 0].cov(combined.iloc[:, 1])
    benchmark_variance = combined.iloc[:, 1].var()

    betas[scheme] = covariance / benchmark_variance

beta_df = pd.DataFrame(
    list(betas.items()),
    columns=["scheme", "beta"]
)

performance_df = performance_df.merge(
    beta_df,
    on="scheme"
)

performance_df[["scheme", "beta"]].round(4)

               scheme    beta
0       Axis_Bluechip  0.0041
1  HDFC_Top100_Direct  1.0000
2      ICICI_Bluechip  0.7695
3      Kotak_Bluechip  0.7713
4    Nippon_Large_Cap  0.8380
5        SBI_Bluechip  0.0131

In [12]:
var_95 = (
    df.groupby("scheme")["daily_return"]
      .quantile(0.05)
      .rename("VaR_95_daily")
      .reset_index()
)

performance_df = performance_df.merge(
    var_95,
    on="scheme"
)

performance_df[
    ["scheme", "VaR_95_daily"]
].round(4)

               scheme  VaR_95_daily
0       Axis_Bluechip        0.0001
1  HDFC_Top100_Direct       -0.0151
2      ICICI_Bluechip       -0.0146
3      Kotak_Bluechip       -0.0142
4    Nippon_Large_Cap       -0.0159
5        SBI_Bluechip       -0.0010

In [13]:
final_columns = [
    "scheme",
    "first_date",
    "last_date",
    "trading_days",
    "annualized_return",
    "annualized_volatility",
    "sharpe_ratio",
    "max_drawdown",
    "beta",
    "VaR_95_daily"
]

final_metrics = performance_df[final_columns].copy()

final_metrics.round(4)

KeyError: "['sharpe_ratio'] not in index"

In [14]:
performance_df["sharpe_ratio"] = (
    performance_df["annualized_return"]
    / performance_df["annualized_volatility"]
)

print(performance_df.columns.tolist())

['scheme', 'first_date', 'last_date', 'first_nav', 'last_nav', 'trading_days', 'annualized_return', 'annualized_volatility', 'max_drawdown', 'beta', 'VaR_95_daily', 'sharpe_ratio']

In [15]:
final_columns = [
    "scheme",
    "first_date",
    "last_date",
    "trading_days",
    "annualized_return",
    "annualized_volatility",
    "sharpe_ratio",
    "max_drawdown",
    "beta",
    "VaR_95_daily"
]

final_metrics = performance_df[final_columns].copy()

final_metrics.round(4)

C:\Users\DELL\AppData\Local\Temp\ipykernel_15440\1361875137.py:16: UserWarning: obj.round has no effect with datetime, timedelta, or period dtypes. Use obj.dt.round(...) instead.
  final_metrics.round(4)

,scheme,first_date,last_date,trading_days,annualized_return,annualized_volatility,sharpe_ratio,max_drawdown,beta,VaR_95_daily
0,Axis_Bluechip,2013-01-01,2026-07-24,3602,0.4756,26.1968,0.0182,-0.0139,0.0041,0.0001
1,HDFC_Top100_Direct,2013-11-19,2026-07-24,3128,0.2479,0.1518,1.6337,-0.4026,1.0000,-0.0151
2,ICICI_Bluechip,2013-01-03,2026-07-24,3344,0.1600,NaN,NaN,-1.0000,0.7695,-0.0146
3,Kotak_Bluechip,2013-01-08,2026-07-24,3338,0.1715,0.1539,1.1141,-0.3343,0.7713,-0.0142
4,Nippon_Large_Cap,2013-01-03,2026-07-24,3335,0.1551,0.1665,0.9315,-0.3996,0.8380,-0.0159
5,SBI_Bluechip,2013-01-03,2026-07-24,3273,0.0026,0.0867,0.0303,-0.3665,0.0131,-0.0010

In [16]:
OUTPUT_DIR = BASE_DIR / "data" / "processed"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

output_path = OUTPUT_DIR / "performance_metrics.csv"

final_metrics.to_csv(output_path, index=False)

print("Performance metrics saved to:")
print(output_path)

Performance metrics saved to:
E:\Mutual Fund Blue\data\processed\performance_metrics.csv

In [17]:
from pathlib import Path

print(output_path.exists())
print(output_path)

True
E:\Mutual Fund Blue\data\processed\performance_metrics.csv

In [18]:
final_metrics.round(4)

C:\Users\DELL\AppData\Local\Temp\ipykernel_15440\4288400418.py:1: UserWarning: obj.round has no effect with datetime, timedelta, or period dtypes. Use obj.dt.round(...) instead.
  final_metrics.round(4)

,scheme,first_date,last_date,trading_days,annualized_return,annualized_volatility,sharpe_ratio,max_drawdown,beta,VaR_95_daily
0,Axis_Bluechip,2013-01-01,2026-07-24,3602,0.4756,26.1968,0.0182,-0.0139,0.0041,0.0001
1,HDFC_Top100_Direct,2013-11-19,2026-07-24,3128,0.2479,0.1518,1.6337,-0.4026,1.0000,-0.0151
2,ICICI_Bluechip,2013-01-03,2026-07-24,3344,0.1600,NaN,NaN,-1.0000,0.7695,-0.0146
3,Kotak_Bluechip,2013-01-08,2026-07-24,3338,0.1715,0.1539,1.1141,-0.3343,0.7713,-0.0142
4,Nippon_Large_Cap,2013-01-03,2026-07-24,3335,0.1551,0.1665,0.9315,-0.3996,0.8380,-0.0159
5,SBI_Bluechip,2013-01-03,2026-07-24,3273,0.0026,0.0867,0.0303,-0.3665,0.0131,-0.0010

## Performance Metrics Methodology

- Annualized return is calculated using 252 trading days.
- Annualized volatility = daily return standard deviation × √252.
- Sharpe Ratio = annualized return / annualized volatility, using a 0% risk-free rate.
- Beta is calculated relative to HDFC Top 100 Direct.
- Maximum Drawdown measures the largest decline from a previous NAV peak.
- VaR is historical 95% daily VaR, based on the 5th percentile of daily returns.